# Generated by Django 4.2.16 on 2024-12-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_blogpost_image_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.product'),
        ),
    ]
